apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: kube-web

patches:
- path: 01-Deployment-Web-App.yml
  target: 
    kind: Deployment
    name: app1-nginx-deployment
    